### ISSUE TITLE
The menu is broken, not collapsing on desktop

### ISSUE THREAD

**Issue by AJV009** [JayKandari/bookhive#105]
Did anyone notice that the menu just broke! Its just not collapsing anymore!

**Comment by shresthaprotejash** [comment]
You can assign it to me. I will resolve it

**Comment by AJV009** [comment]
Hey @shresthaprotejash  we would love to have you collaborating but its a kind of locked project for now as the base is yet to be build and under work so we aren't assigning issues to anyone. (as much as I know, maybe the maintainer @JayKandari will comment on this)
We will open it up for public soon, until then find other repos for Hacktober and have a Happy Weekend!.

**Comment by AJV009** [comment]
Before Clicking on collapse
![12](https://user-images.githubusercontent.com/42465795/94995740-f27a6f00-05bd-11eb-9e25-61dee7a50893.png)

After Clicking on collapse
![13](https://user-images.githubusercontent.com/42465795/94995742-f3ab9c00-05bd-11eb-8f98-a485ce03bde1.png)
@pragzii3896 @shriaas2898

**Comment by shriaas2898** [comment]
It could be happening because we are using grid I'll try to fix this
