### ISSUE TITLE
Privileged pages are accessible without loggin-in.

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#107]
`admindash` and other privileged pages are accessible through URL without loggin-in. Probably something wrong with the session code.

**Comment by AJV009** [comment]
are thinks breaking more and more over time!
I guess we will need to remove the session related stuff from menu and make it into another class
and then have a redirection thing called in the template itself

**Comment by shriaas2898** [comment]
> are thinks breaking more and more over time!
> I guess we will need to remove the session related stuff from menu and make it into another class
> and then have a redirection thing called in the template itself

Ya that could work.

**Comment by AJV009** [comment]
@shriaas2898  it would be helpful if you could also mention the url where the admin control are exposed

**Comment by AJV009** [comment]
@shriaas2898  FIXED
