### ISSUE TITLE
Convert table to list

### ISSUE THREAD

**Issue by anjali-rathod** [JayKandari/bookhive#117]
Convert all tables to lists

**Comment by AJV009** [comment]
https://github.com/JayKandari/bookhive/issues/97
kind of a duplicate issue

**Comment by anjali-rathod** [comment]
@AJV009 duplicate to which one?

**Comment by AJV009** [comment]
are #97  we are discussing the same issue there

**Comment by anjali-rathod** [comment]
Ah . Ok .

**Comment by shriaas2898** [comment]
Files to edit
* edituserlist.php
* books.php
* searchbook.php
