### ISSUE TITLE
UI Designing Pages

### ISSUE THREAD

**Issue by pragatikanade** [JayKandari/bookhive#12]
Create UI for pages

- Homepage(search book,sign in, sign up,about us, contact us)
- Admin dashboard(add book,edit book->list of all books with edit delete option,user edit,personal info edit,sign out)

**Comment by pragatikanade** [comment]
Created all the UI pages.

**Comment by guptahemant** [comment]
Issue should be closed once an MR has been merged for resolving this issue.

**Comment by pragatikanade** [comment]
Created UI pages.
