### ISSUE TITLE
Create get and set methods for session variable in SessionCookie class

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#127]
To avoid using `$_SESSION` variable directly in the code 

* Create getter and setter methods in `SessionCookie` class.
* Create method to store and show session messages.

This kind of code should be avoided: 
Direct use of session variable:
```
if ($_SESSION['admin'] == 'admin') {
```
Setting messages in session variable:
```
      if ($stmt->execute($valArr) === TRUE) {
         $_SESSION["success"] = "Details updated successfully!";
      } 
```

**Comment by AJV009** [comment]
> To avoid using `$_SESSION` variable directly in the code
> 
>     * Create getter and setter methods in `SessionCookie` class.
> 
>     * Create method to store and show session messages.
> 
> 
> This kind of code should be avoided:
> Direct use of session variable:
> 
> ```
> if ($_SESSION['admin'] == 'admin') {
> ```
> 
> Setting messages in session variable:
> 
> ```
>       if ($stmt->execute($valArr) === TRUE) {
>          $_SESSION["success"] = "Details updated successfully!";
>       } 
> ```

can you give an example.

**Comment by shriaas2898** [comment]
Instead of `$_SESSION["success"] = "Details updated successfully!";` we should use a method like `$session->setStatusMessage("Details updated successfully!");`
Where `$session` is an object of `SessionCookie` class.

**Comment by AJV009** [comment]
> Instead of `$_SESSION["success"] = "Details updated successfully!";` we should use a method like `$session->setStatusMessage("Details updated successfully!");`
> Where `$session` is an object of `SessionCookie` class.

mmmmm got it!
yeah will do
but just out of curiosity "Why is it bad to directly assign values in session?"

**Comment by shriaas2898** [comment]
To be fixed in future scope
