### ISSUE TITLE
Search bar with filters

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#13]
Create a search bar to search book by:
* Title
* Category
* Author
And sort by date added

**Comment by AJV009** [comment]
Anybody working on this?
You can use some kind of query using `SELECT` and `LIKE`
But for prepared statements there is some modifications as much as I know

**Comment by AJV009** [comment]
@shriaas2898  @anjali-rathod @pragzii3896  any idea who was working on this?

**Comment by anjali-rathod** [comment]
Aastha has the code ready . She will make composer and the search bar addition to my code . @AJV009

**Comment by AJV009** [comment]
> Aastha has the code ready . She will make composer and the search bar addition to my code . @AJV009

mmm okay so a PR will be coming soon, right?

**Comment by shriaas2898** [comment]
Yes working on thatt! @AJV009

**Comment by JayKandari** [comment]
Basic search is working. Thus closing.
