### ISSUE TITLE
Connection to database should be fetched from dbcreds.json 

### ISSUE THREAD

**Issue by JayKandari** [JayKandari/bookhive#29]
Currently, the database connections are hardcoded directly in the files. 
* resources/src/user.php
* resources/src/books.php

These should ideally be fetched from the `dbcreds.json` file which should be created manually.

Check `config.php` file, to see which variables to use.

**Comment by guptahemant** [comment]
I would even say that this should be extended to use a particular database class which is reponsible for setting up database connection and should also be responsible for basic queries if possible.

**Comment by AJV009** [comment]
@anjali-rathod  even I mean something like as @guptahemant mentioned

**Comment by AJV009** [comment]
@anjali-rathod I have transformed the config file into a class file which can be used the same way I have called the redirect function in the sessionCookie.php in root/resource/src
now you can make changes easily, and am sorry about the old PR with not much tested code which I have now fixed and tested.
so in your code it would kind of look like **(here I have just printed the whole config file)**
```php
...
require $_SERVER['DOCUMENT_ROOT'].'/vendor/autoload.php';
...
$this->config = new ProjectConfig;
...
var_dump($this->config->config);
```

**Comment by AJV009** [comment]
@anjali-rathod have you made these changes yet?
I think no, so can you change it asap and make a PR asap. so that we can close this issue asap.
its as simple as "asap" 😏️

**Comment by AJV009** [comment]
@JayKandari  @guptahemant @anjali-rathod @shriaas2898  I have made the required changes if tested or at least as per your assumptions you guys feel its good then we can merge https://github.com/JayKandari/bookhive/pull/42 and close this issue
