### ISSUE TITLE
Move common header/footer markups in a common template file

### ISSUE THREAD

**Issue by JayKandari** [JayKandari/bookhive#30]
All the pages files inside the `public-html` directory have their own `<HTML>` `<head>` etc set.

Most of these can be moved into a common file and then these common files can be included in the respective files at appropriate positions.

**Comment by AJV009** [comment]
@JayKandari I think @pragzii3896 made three different headers which is being called for different use like anonymous, user and admin.

**Comment by AJV009** [comment]
@pragzii3896  I just inspected the code looks like we can reuse some components as with current site design there are some restrictions, feel free to reach out in a call to fix em.

**Comment by shriaas2898** [comment]
A part of this (creating, header and sidebar) is covered in #72
Things to do now:
* Create a class to combine php headers, menus and main content and render it.
* Use functions from Menu class for header and sidebar, get main content from individual files.

**Comment by shriaas2898** [comment]
If anyone is working on this please make sure to:
* Use `<header>` tag for header
* Give `sidebar` class to div for sidebar
* Give `main-content` class to the div containing content of that page
As these are used by CSS to display the whole page as grid.

**Comment by AJV009** [comment]
@shriaas2898 if I want to work on this, what should I do. What is this issue actually about!

**Comment by shriaas2898** [comment]
Currently we have `Menu` class which renders the elements of `header` `navigation` and `sidebar`, however there is still a lot of code repetition as these functions (for creating menu) needs to be called in every file, also there is some session code which is repeating in several files. The goal is to just keep a block i.e a `div` with `main-content` in the file which contains content specific to that particular file and create an interface (class, method anything) which combines elements from `Menu` extra `session/config` code if any and the main content of that file and renders it.

This can help: https://code.tutsplus.com/tutorials/organize-your-next-php-project-the-right-way--net-5873

**Comment by AJV009** [comment]
@shriaas2898  I have a hacky idea!
How about we pass the main content to a function which would render the whole page?

**Comment by shriaas2898** [comment]
> @shriaas2898 I have a hacky idea!
> How about we pass the main content to a function which would render the whole page?

Ya! that is the intent!

**Comment by JayKandari** [comment]
This seems fixed. cc: @AJV009
