### ISSUE TITLE
Remove closing php tags from PHP files if the files only contains PHP code

### ISSUE THREAD

**Issue by JayKandari** [JayKandari/bookhive#38]
The closing `?>` tag for php files can be removed if the file contains only PHP code and not any HTML. 

> It is recommended that a closing PHP tag shall be omitted in a file containing only PHP code so that occurrences of accidental whitespace or new lines being added after the PHP closing tag, which may start output buffering causing uncalled for effects can be avoided.

Read more: https://www.w3resource.com/php/syntax/syntax.php

**Comment by AJV009** [comment]
I have fixed it so now you can close this issue.

**Comment by JayKandari** [comment]
This is already done. Closing
