### ISSUE TITLE
Fix the book issue function.

### ISSUE THREAD

**Issue by anjali-rathod** [JayKandari/bookhive#45]
Make database connectivity to the function.

**Comment by anjali-rathod** [comment]
Can I take this issue?

**Comment by AJV009** [comment]
to which function/file you actually mean?

**Comment by anjali-rathod** [comment]
books.php and login.php

**Comment by AJV009** [comment]
its fixed na?
Ha there are some code which you can remove!

**Comment by anjali-rathod** [comment]
Not fixed. It needs to be modified. What code is to be removed?

**Comment by AJV009** [comment]
I have set FETCH ARRAY as default so you need not specify it in the code
+ your code uses dbconn.php for connection
so see carefully before use

**Comment by AJV009** [comment]
@anjali-rathod  can you make the PR asap so that I can work on some optimizations I can see in the books.php and user.php

**Comment by AJV009** [comment]
@anjali-rathod To fetch data from a result set: Fetch data from a result set by calling one of the fetch methods: To return a single row from a result set as an array or object, call the PDOStatement::fetch method. To return all of the rows from the result set as an array of arrays or objects, call the PDOStatement::fetchAll method.

**Comment by anjali-rathod** [comment]
We will have to make changes to all respective codes if we fetch in array format
