### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by pragatikanade** [JayKandari/bookhive#46]

**Comment by AJV009** [comment]
provide a description tooo

**Comment by shriaas2898** [comment]
ToDo Responsive:
* [x] Login
* [x] Register
* [x] Add book
* [x] Book Issued
* [ ] About
* [ ] Contact 
* [ ] Home
* [ ] Edit book
* [ ] Edit User

**Comment by shriaas2898** [comment]
Further continued #113, #114 and  #117.
Can be closed.
