### ISSUE TITLE
Change sidebar menus user is logged in

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#47]
Add a condition in `index.php` to change menu items when user is logged in

**Comment by AJV009** [comment]
@shriaas2898  I guess this https://github.com/JayKandari/bookhive/issues/62 issue is being fixed so am closing the previous one and continue here.

**Comment by shriaas2898** [comment]
No don't close it yet! Let me raise a PR for it first

**Comment by AJV009** [comment]
@shriaas2898  I meant as both issue will eventually point to one PR I closed the old one and let this one remain until PR is merged

**Comment by AJV009** [comment]
@shriaas2898  this is fixed right, why not close it?
OR @JayKandari  / @guptahemant  can close this too
