### ISSUE TITLE
Highlight active menu item in sidebar

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#48]
The active menu item in sidebar should have different background color

**Comment by AJV009** [comment]
+ animate three lines to a big X (cross) when the menu is collapsed
+ Add some spacing between menu icons when collapsed
+ Make default position collapsed

**Comment by AJV009** [comment]
@shriaas2898  am working on this!

**Comment by shriaas2898** [comment]
Cool! The class `active-menu` is already defined in the tag you just have to change the bgcolor.

**Comment by AJV009** [comment]
YES I SAW

**Comment by AJV009** [comment]
Fixed in https://github.com/JayKandari/bookhive/pull/81
@shriaas2898  please close

**Comment by pragatikanade** [comment]
@AJV009 you did this right?

**Comment by AJV009** [comment]
@pragzii3896 check the linked PR https://github.com/JayKandari/bookhive/pull/81

**Comment by pragatikanade** [comment]
@AJV009 yes. I saw :+1:
