### ISSUE TITLE
Session implementation

### ISSUE THREAD

**Issue by AJV009** [JayKandari/bookhive#5]
Am hunting more on the sessions and DB query part, hoping to develop a highly reusable DB Query and Session manager while keeping OOPs and security in mind. 
+ Want to try the PDO approach instead of mysqli functions as it more universally acceptable across a variety of DBMS.

**Comment by JayKandari** [comment]
Yes PDO is a good way to move forward.

**Comment by AJV009** [comment]
I just changed the title because Anjali said she would like to do the DB part

**Comment by AJV009** [comment]
@JayKandari  @guptahemant 
Cant I call a function inside the class constructor?
this function resides in the same class

**Comment by AJV009** [comment]
sorry i got it

**Comment by AJV009** [comment]
@guptahemant I guess it will be okay to close this issues, right?

**Comment by guptahemant** [comment]
Yes if you feel that session management does not need any updates, If you need to do more updates make sure to add new issues for the same.
