### ISSUE TITLE
dbConn new connectivity options

### ISSUE THREAD

**Issue by AJV009** [JayKandari/bookhive#51]
@anjali-rathod with the new connectivity options provided in dbConn you can pass queries directly to exeQuery which returns output of fetchall()
please test before use as there were some complaints from @shriaas2898 that the array approach didnt work.
BUT it did work on my side

**Comment by AJV009** [comment]
@shriaas2898  can you give a confirmation that passing array in the exeQuery is not working?
So that I can work on it

**Comment by shriaas2898** [comment]
Yes I tried this `$conn->exeQuery($query,[$_POST["search_query"]])` and also this `$conn->exeQuery($query,array($_POST["search_query"]))`
Both are not working

**Comment by AJV009** [comment]
```php
<?php
require $_SERVER['DOCUMENT_ROOT'].'/../vendor/autoload.php';
use PDO_CONN\Connection;
$conn = new Connection;
$conn->exeQuery("insert into user (uname, email, pass, type) values (? , ?, ?, ?) ", [ "blah", "blah", "blah", "user" ] );
```
tested working

**Comment by AJV009** [comment]
@anjali-rathod  please see this example above, its a working prepared statement. I have tested it!
I like this PDO approach than mysqli, its less complicated.

**Comment by AJV009** [comment]
@anjali-rathod  I'll work on this?

**Comment by anjali-rathod** [comment]
Lets work on all the queries. I think my code has many duplicacy

**Comment by AJV009** [comment]
> Lets work on all the queries. I think my code has many duplicacy

Lets make it asap.

**Comment by AJV009** [comment]
Refactoring Books.php is really difficult now as the logic would require a ton of changes
