### ISSUE TITLE
All session code in a session file

### ISSUE THREAD

**Issue by anjali-rathod** [JayKandari/bookhive#58]

**Comment by AJV009** [comment]
Am sorry, I had been busy with some work. I understood the issue.
AND also dont forget to add a description to the issue while opening.

**Comment by AJV009** [comment]
Fixed in https://github.com/JayKandari/bookhive/pull/61

**Comment by pragatikanade** [comment]
@anjali-rathod anjali this issue is fixed. Can you please close this.
