### ISSUE TITLE
Front end CSS and SCSS related changes

### ISSUE THREAD

**Issue by guptahemant** [JayKandari/bookhive#60]
- Folder structure - There should be one css folder and scss folder
- scss folder - should contain all the scss files - along with one main.scss ( which includes all the scss )
- css folder should contain for now one css file ( main.css ). - other css files should be removed from the code base
- We should use gulp to convert the main.scss file to css/main.css file ( we have done the exercise how gulp task is used to achieve this  )
- For colors we should define it as variables in color.scss and then used at other places

**Comment by AJV009** [comment]
I'll work on this after this get merged https://github.com/JayKandari/bookhive/pull/63
Because this PR largely edits CSS/SCSS files and configuration.

**Comment by pragatikanade** [comment]
@guptahemant this issue is resolved. can you please close this issue?

**Comment by guptahemant** [comment]
Marking as done
