### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by AJV009** [JayKandari/bookhive#7]
We would love the repo to be renamed to Bookhive. (Our application theme is related to a Hive and Book)

**Comment by JayKandari** [comment]
Renamed the repository to bookhive. https://github.com/JayKandari/bookhive

Please update your `upstream` branch. You may need to run following commands. 

- `git remote remove upstream` && 
- `git remote add upstream https://github.com/JayKandari/bookhive.git`
