### ISSUE TITLE
Auto crop/resize uploaded book images

### ISSUE THREAD

**Issue by AJV009** [JayKandari/bookhive#70]
Auto crop or resize book images uploaded through addbook admin page

**Comment by AJV009** [comment]
@shriaas2898 you working on this?

**Comment by shriaas2898** [comment]
@AJV009 I am creating variables for image sizes does that works? @pragzii3896 @rahulsavaria?

**Comment by pragatikanade** [comment]
@shriaas2898  hmm yes.. i also created variables for colours. You can create variables for anything which is going to use many times/globally.

**Comment by AJV009** [comment]
@shriaas2898 this is fixed na?
May I close it?

**Comment by shriaas2898** [comment]
We just had to display all the book covers of same size right? In home page and new collection?

**Comment by AJV009** [comment]
:unamused: :yellow_circle:

**Comment by AJV009** [comment]
@shriaas2898  will this help -> https://www.sitepoint.com/crop-and-resize-images-with-imagemagick/
