### ISSUE TITLE
Create constants for user role

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#73]
* Create constant to represent user roles: `anon`,`user` and `admin`
* Include these constants in `User` class
* Modify session to use constants instead of string for roles

**Comment by AJV009** [comment]
this is fixed right?
@shriaas2898  why not close this!

**Comment by shriaas2898** [comment]
No this is yet to be implemented. Code is using hard coded values right now.

**Comment by AJV009** [comment]
OOOOps sorry

**Comment by AJV009** [comment]
mmm how can I work on this?

we are storing those details in the session na!

**Comment by shriaas2898** [comment]
We are storing string in session right 'admin' and 'user' and wherever we are comparing. So insted we can define ROLE_ADMIN or ROLE_USER in config file.

**Comment by AJV009** [comment]
mmmm ookay

**Comment by AJV009** [comment]
> We are storing string in session right 'admin' and 'user' and wherever we are comparing. So insted we can define ROLE_ADMIN or ROLE_USER in config file.

mmm I was thinking about this but couldn't understand a lot! Am bit confused!
What is the actual goal here, what advantage are we getting from storing those values in constant.
If you mean somebody should not tamper the session vars then it is not good because another admin can make a user an admin while he/she is using the system!
Am still confused about why constants

**Comment by shriaas2898** [comment]
Suppose I want to change value stored in session from `user` to `authenticated user`  I would have to change it everywhere right wherever I am checking the role, so instead its better if I define that as a constant and use the constant everywhere rather than using hard-coded values.

**Comment by AJV009** [comment]
> Suppose I want to change value stored in session from `user` to `authenticated user` I would have to change it everywhere right wherever I am checking the role, so instead its better if I define that as a constant and use the constant everywhere rather than using hard-coded values.

no you dont have to!
as soon as you change it somewhere in session every next page will work based on that session which says you are a authen....user

**Comment by shriaas2898** [comment]
To be fixed in future scope
