### ISSUE TITLE
Add documentation EVRYWHERE

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#77]
Most of the code is undocumented right now, add documentation to explain why the code is working the way its working.

**Comment by AJV009** [comment]
SO TRUE, I THINK OF IT BUT I FEEL LAZY LATER

**Comment by AJV009** [comment]
This issue is for everyone to fix who is writing new code or improving old code! @pragzii3896 @anjali-rathod @shriaas2898

**Comment by AJV009** [comment]
@shriaas2898 we can close this!

**Comment by shriaas2898** [comment]
I don't think there is enough documentation everywhere🤔

**Comment by AJV009** [comment]
ahhh you add it over time na!
Are we going to keep this opened forever? 
Because documentation is going to be added everytime!

**Comment by shriaas2898** [comment]
Until we have enough documentation we have to keep it open

**Comment by AJV009** [comment]
> Until we have enough documentation we have to keep it open

OK fine! :neutral_face:

**Comment by shriaas2898** [comment]
Minor fixes left, to be fixed in future scope
