### ISSUE TITLE
Implement IMAGE update code

### ISSUE THREAD

**Issue by anjali-rathod** [JayKandari/bookhive#78]
In the edit book page , the update of all other fields have been implemented other than for image.

**Comment by anjali-rathod** [comment]
@pragzii3896 if you could fix this? Cause I am currently working on the CSS part.

**Comment by pragatikanade** [comment]
@anjali-rathod sure i will work on that when i finish php validation. :+1:

**Comment by anjali-rathod** [comment]
Thank you
