### ISSUE TITLE
Faulty Hamburger menu

### ISSUE THREAD

**Issue by AJV009** [JayKandari/bookhive#90]
stairs like effect to the right side of the hamburger menu when in mobile view

**Comment by shriaas2898** [comment]
Also in the mobile view color of text of active menu is different:
![image](https://user-images.githubusercontent.com/26863344/94770271-d2865800-03d1-11eb-94c5-09b3e0763556.png)
While it is not there in the laptop view:
![image](https://user-images.githubusercontent.com/26863344/94770311-e9c54580-03d1-11eb-986d-52d42cf3b22b.png)

**Comment by shriaas2898** [comment]
@AJV009 We can close this

**Comment by AJV009** [comment]
fine!
