### ISSUE TITLE
Eliminate use of table

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#97]
The width of table is overflowing the body:
![image](https://user-images.githubusercontent.com/26863344/94809537-5eb77000-0410-11eb-8943-ca908b51ee33.png)

This is probably because the media query is working on very large screen width `@media(max-width:1260px)` there can be other factors too.

**Comment by AJV009** [comment]
The only issue no body wants to talk about! 
:laughing:

**Comment by AJV009** [comment]
Well we can do something!
Eliminate the need of a table everywhere in the app because it sucks
and have loop a div box or something like that!
OR just dont have a lot of columns like in the edit book page which is not responsive on phones I guess!

**Comment by shriaas2898** [comment]
Continued in #117
