### ISSUE TITLE
Link for user and admin dashboard

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#98]
Currently user can only access the dashboard when they login but there is no other way to go back if the click on some other link, add a link in the `user name` or `profile photo` which redirects user to their dashboard
![image](https://user-images.githubusercontent.com/26863344/94810313-7d6a3680-0411-11eb-8ccc-c510e5b1b2da.png)

**Comment by pragatikanade** [comment]
Okay :+1:

**Comment by shriaas2898** [comment]
@pragzii3896  are you taking up the issue?

**Comment by pragatikanade** [comment]
@shriaas2898  hmm may be yes.. let me first do display messages thing .. then I will try to do this.

**Comment by pragatikanade** [comment]
@shriaas2898  I need to add same dashboard link to image or name right?

**Comment by shriaas2898** [comment]
Yes you need to add link on image or name based on role i.e
* link for `admindash` for `admin`
* link for `userdash` for `user`
* link for `index` for `anonymous`

**Comment by pragatikanade** [comment]
Hmm cool I will implement.. then will cross check first :+1:
