### ISSUE TITLE
Content in admin dashboard

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#99]
The `admindash` page is currently empty, some content should be added their for example list of all the issued books or a welcome message

**Comment by pragatikanade** [comment]
okay :+1:

**Comment by shriaas2898** [comment]
@pragzii3896 are you taking up the issue?

**Comment by AJV009** [comment]
How about some stats on admin dash!

**Comment by shriaas2898** [comment]
Will need to add more functions for it @AJV009

**Comment by AJV009** [comment]
mmmm i think that would be bit extra and time consuming lets just fix the current issue then think about it!
